### ISSUE TITLE
Black toast appears in light theme when note is copied to clipboard

### ISSUE THREAD

**Issue by jestintab** [robertmathew/TapNote#2]
Black toast appears in light theme when note is copied to clipboard in playstore. Please update that in playstore, I don't know about that in github code

**Comment by robertmathew** [comment]
According to Material Design guidelines, snackbar background should be grey(#323232) 
https://www.google.co.in/design/spec/components/snackbars-toasts.html#snackbars-toasts-specs

**Comment by jestintab** [comment]
Then the text should be in white. I can't see the what the text says

**Comment by robertmathew** [comment]
Snackbar text is white. Check your version. Latest 0.5.1(17)

**Comment by robertmathew** [comment]
Fix 8771416b4ac928720de996e34a04570d16acc5ee

**Comment by robertmathew** [comment]
Download apk from [Release] (https://github.com/robertmathew/TapNote/releases) or wait for Play Store to update.

**Comment by jestintab** [comment]
okay thanks robo !
